### ISSUE TITLE
Improve variable display in data viewer

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/mortimer#100]
Data viewer only shows variables present in older (maybe the first?) experiment versions. Example: If V100 exists in version 0.3 but not in 0.2 of an experiment, the data viewer in mortimer will not display this variable, also for datasets from version 0.3 that contain it. Could we configure the data viewer to generate the Table Header from the last experiment version instead of the first?

**Comment by jobrachem** [comment]
See #77
