### ISSUE TITLE
Experiment creation: Selection of script.py not always working

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/mortimer#111]
Multiple users have reportes cases, in which a script.py file was selected during experiment creation in mortimer, but the script was not successfully transferred. However, there is no error message in these instances.

**Comment by jobrachem** [comment]
Maybe #91 will make this issue obsolete?

**Comment by jobrachem** [comment]
No, this is a separate issue. Maybe we will just deactivate both buttons.
