### ISSUE TITLE
Precondition Failed error on date change

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/mortimer#81]
Active experiment sessions get a _Precondition Failed_ error when the date changes on midnight. The error code 412 points to the client not being able to authenticate the current session with the server. The session seems to get lost by the server. As far as I can see, the client side cookie does not change on midnight, therefore I assume the problem lies with the flask server.

**Comment by ctreffe** [comment]
From the logfile:

```

ctreffe@alfredo3 /home/alfred/www/mortimer3 % cat mortimer.log
2022-04-27 20:13:52,980 - WARNING - Experiment route called, but there was no session id in the session cookie.
2022-04-28 00:00:35,236 - WARNING - Tried to access experiment with key 'sid-3b3b5f06-79f9-41eb-9d7c-159660cd79c3'. Available Keys: []
2022-04-28 00:00:46,410 - WARNING - Tried to access experiment with key 'sid-3b3b5f06-79f9-41eb-9d7c-159660cd79c3'. Available Keys: []
```

**Comment by ctreffe** [comment]
The above problem is most likely caused by logrotate, as I initially suspected. See the Apache 2 logrotate configuration file:

```
root@alfredo3 /etc/logrotate.d # cat apache2
/var/log/apache2/*.log {
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
        create 640 root adm
        sharedscripts
        postrotate
                if invoke-rc.d apache2 status > /dev/null 2>&1; then \
                    invoke-rc.d apache2 reload > /dev/null 2>&1; \
                fi;
        endscript
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi; \
        endscript
}
```

The postrotate hook seems to reload the apache server after every rotation. The apache status shows a reload immediately before the mortimer logfile shows an empty session list. The log is rotated every day at midnight and from what I understand of the current logrotate configuration, a restart would be necessary for the apache server to start logging into the newly created file after rotation.

Here is a possible solution to the issue:

https://unix.stackexchange.com/questions/47688/how-to-avoid-apache-reload-when-rotating-logs

**Comment by jobrachem** [comment]
Ooh nice one!

**Comment by jobrachem** [comment]
@ctreffe can this issue be closed?
