### ISSUE TITLE
Last subject activity shows only time, not date

### ISSUE THREAD

**Issue by slussinator** [ctreffe/mortimer#99]
Hello, 

I frequently stumble upon this: I look into my experiments and wonder, when the last subject participated. Unfortunately, on the main page under "last subject activity" it only says the time, but not the date (It does tell you the exact date and time of the first activity though). Could you possibly add the date as well? 

Thank you so much!

**Comment by jobrachem** [comment]
Valid point, we should indeed update the display to show the date.

**Comment by jobrachem** [comment]
Was already addressed in https://github.com/ctreffe/mortimer/commit/0e5cab89694506e4b994fae912345d896daf808d
